# Generated by Django 4.0.2 on 2022-04-26 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('owner_projects', 'Project'), ('supporter_pledges', 'Pledge')], max_length=20)),
                ('badge_goal', models.PositiveIntegerField()),
                ('users', models.ManyToManyField(related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('badge_type', 'badge_goal')},
            },
        ),
    ]
