# Generated by Django 4.0.2 on 2022-04-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_pledge_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, default='Uncategorised', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_projects', to='projects.category'),
        ),
    ]
